#!/usr/bin/env bash

op=$( echo -e " Shutdown\n Reboot\n Suspend\n Lock\n Logout\n Hibernate" | rofi -i -dmenu | awk '{print tolower($2)}' )

case $op in
        shutdown)
                sudo poweroff
                ;;
        reboot)
                sudo reboot
                ;;
        suspend)
                swaylock ; sudo systemctl suspend
                ;;
        lock)
        swaylock
                ;;
        logout)
                kill $(ps -A | grep -i gvfs | awk '{print $1}') >/dev/null 2>&1 ; \
                pkill -f swayfader sway_autotiling clipman wl-copy wl-paste >/dev/null 2>&1; \
                mpc -q stop ; \
                pkill -f seatd >/dev/null 2>&1 ; \
                swaymsg exit ; \
                ;;
        hibernate)
                swaylock ; sudo systemctl hibernate
                ;;
esac
