#!/usr/bin/env bash

##
## Setzten von Umgebungsvariablen
##

## falls nicht der Standard SSH Key verwendet wird können
## Sie hier den Pfad zu Ihrem private Key angeben
# export BORG_RSH="ssh -i /home/userXY/.ssh/id_ed25519"

## Damit das Passwort vom Repository nicht eingegeben werden muss
## kann es in der Umgepungsvariable gesetzt werden
# export BORG_PASSPHRASE="top_secret_passphrase"

##
## Setzten von Variablen
##

LOG="$home/backup/borg_backup.log"
BACKUP_USER=""
REPOSITORY_DIR="$HOSTNAME"

## Hinweis: Für die Verwendung mit einem Backup-Account muss
## 'your-storagebox.de' in 'your-backup.de' geändert werden.

REPOSITORY="ssh://${BACKUP_USER}@${BACKUP_USER}.your-storagebox.de:23/./repo/borg/${REPOSITORY_DIR}"

##
## Ausgabe in Logdatei schreiben
##
if ! [ -f "${LOG}" ]; then
    mkdir "$HOME/backup" &>/dev/null
    touch "${LOG}"
fi
exec > >(tee -i ${LOG})
exec 2>&1

echo "###### Backup gestartet: $(date) ######"

##
## An dieser Stelle können verschiedene Aufgaben vor der
## Übertragung der Dateien ausgeführt werden, wie z.B.
##
## - Liste der installierten Software erstellen
## - Datenbank Dump erstellen
##

##
## Dateien ins Repository übertragen
## Gesichert werden hier beispielsweise die Ordner root, etc,
## var/www und home
## Ausserdem finden Sie hier gleich noch eine Liste Excludes,
## die in kein Backup sollten und somit per default ausgeschlossen
## werden.
##

echo "Übertrage Dateien ..."
borg create -v --stats                   \
    $REPOSITORY::'{now:%Y-%m-%d_%H:%M}'  \
    /home                                \
    --exclude /dev                       \
    --exclude /proc                      \
    --exclude /sys                       \
    --exclude /var/run                   \
    --exclude /run                       \
    --exclude /lost+found                \
    --exclude /mnt                       \
    --exclude /var/lib/lxcfs             \
    --exclude ~/videos                   \
    --exclude ~/repos                    \
    --exclude ~/nextcloud                \
    --exclude ~/music                    \
    --exclude ~/downloads                \
    --exclude ~/backup                   \
    --exclude ~/.cache                   \
    --exclude ~/.pki                     \
    --exclude ~/.npm                     \
    --exclude ~/.mozilla                 \
    --exclude ~/.lyrics                  \
    --exclude ~/.hplip                   \
    --exclude ~/.local/state             \

echo "###### Backup beendet: $(date) ######"
