#!/usr/bin/env bash
#set -euC

tmux="tmux"
SESSION=scratchpad

attach() {
    [ -n "${TMUX:-}" ] &&
        tmux switch-client -t $SESSION ||
        tmux attach-session -t $SESSION
}

# Only create tmux session if it doesn't already exist
if tmux has-session -t $SESSION 2>/dev/null; then
  attach
  exit 0
fi
    # Create a new session, named $SESSION, and detach from it
    $tmux new-session -d -s     $SESSION
    $tmux rename-window -t      $SESSION:1      'shell'

    # Select and attach session
    $tmux select-window -t      $SESSION:1
    $tmux attach        -t      $SESSION
